version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./metabase-data:/metabase-data
    env_file:
      - .env
    ports:
      - "3001:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - metabase
