# docker-compose.yml
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MB_DB_TYPE=${MB_DB_TYPE?Variable not set}
      - MB_DB_DBNAME=${MB_DB_DBNAME?Variable not set}
      - MB_DB_PORT=${MB_DB_PORT?Variable not set}
      - MB_DB_USER=${MB_DB_USER?Variable not set}
      - MB_DB_PASS=${MB_DB_PASS?Variable not set}
      - MB_ENCRYPTION_SECRET_KEY=${MB_ENCRYPTION_SECRET_KEY?Variable not set}

  metabase_db:
    image: postgres:12
    container_name: metabase_db
    restart: always
    volumes:
      - ./app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"

volumes:
  app-db-data:
