# docker-compose.yml
services:
  metabase:
    image: metabase/metabase:v0.50.29
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MB_DB_TYPE=${MB_DB_TYPE?Variable not set}
      - MB_DB_DBNAME=${MB_DB_DBNAME?Variable not set}
      - MB_DB_PORT=${MB_DB_PORT?Variable not set}
      - MB_DB_USER=${MB_DB_USER?Variable not set}
      - MB_DB_PASS=${MB_DB_PASS?Variable not set}
      - MB_ENCRYPTION_SECRET_KEY=${MB_ENCRYPTION_SECRET_KEY?Variable not set}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-streamlit-http.rule=Host(`metabase.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-streamlit-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME?Variable not set}-streamlit-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME?Variable not set}-streamlit-https.rule=Host(`metabase.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-streamlit-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME?Variable not set}-streamlit-https.tls=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-streamlit-https.tls.certresolver=le
      - traefik.http.services.${STACK_NAME?Variable not set}-streamlit.loadbalancer.server.port=3000
    networks:
      - traefik-public
      - default

networks:
  traefik-public:
    # Allow setting it to false for testing
    external: true
